#!/usr/bin/env bash
set -e

# Yaade CLI Installer
# This script installs yaade as a globally available CLI tool

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIN_PYTHON_VERSION="3.12"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Check Python version
check_python() {
    info "Checking Python version..."

    if command -v python3 &> /dev/null; then
        PYTHON_CMD="python3"
    elif command -v python &> /dev/null; then
        PYTHON_CMD="python"
    else
        error "Python is not installed. Please install Python ${MIN_PYTHON_VERSION}+ first."
    fi

    PYTHON_VERSION=$($PYTHON_CMD -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    MAJOR=$(echo "$PYTHON_VERSION" | cut -d. -f1)
    MINOR=$(echo "$PYTHON_VERSION" | cut -d. -f2)

    if [[ "$MAJOR" -lt 3 ]] || [[ "$MAJOR" -eq 3 && "$MINOR" -lt 12 ]]; then
        error "Python ${MIN_PYTHON_VERSION}+ is required. Found: Python ${PYTHON_VERSION}"
    fi

    success "Found Python ${PYTHON_VERSION}"
}

# Check and install uv if needed
check_uv() {
    info "Checking for uv package manager..."

    if command -v uv &> /dev/null; then
        success "uv is already installed"
        return 0
    fi

    warn "uv is not installed. Installing..."

    if [[ "$OSTYPE" == "darwin"* ]] || [[ "$OSTYPE" == "linux-gnu"* ]]; then
        curl -LsSf https://astral.sh/uv/install.sh | sh
        # Source the new PATH
        export PATH="$HOME/.local/bin:$PATH"
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
        powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
    else
        error "Unsupported OS. Please install uv manually: https://docs.astral.sh/uv/getting-started/installation/"
    fi

    if command -v uv &> /dev/null; then
        success "uv installed successfully"
    else
        error "Failed to install uv. Please install manually: https://docs.astral.sh/uv/getting-started/installation/"
    fi
}

# Determine install location
get_install_dir() {
    if [[ -n "$YAADE_INSTALL_DIR" ]]; then
        INSTALL_DIR="$YAADE_INSTALL_DIR"
    elif [[ -d "$HOME/.local/bin" ]]; then
        INSTALL_DIR="$HOME/.local/bin"
    elif [[ -d "/usr/local/bin" ]] && [[ -w "/usr/local/bin" ]]; then
        INSTALL_DIR="/usr/local/bin"
    else
        INSTALL_DIR="$HOME/.local/bin"
        mkdir -p "$INSTALL_DIR"
    fi

    info "Install directory: $INSTALL_DIR"
}

# Install yaade using uv
install_yaade() {
    info "Installing yaade..."

    cd "$SCRIPT_DIR"

    # Sync dependencies and install the package
    uv sync

    success "Dependencies installed"
}

# Create wrapper script for global access
create_wrapper() {
    info "Creating global wrapper script..."

    WRAPPER_PATH="$INSTALL_DIR/yaade"

    cat > "$WRAPPER_PATH" << EOF
#!/usr/bin/env bash
# Yaade CLI wrapper - auto-generated by install.sh
cd "$SCRIPT_DIR" && exec uv run yaade "\$@"
EOF

    chmod +x "$WRAPPER_PATH"
    success "Wrapper created at $WRAPPER_PATH"
}

# Check if install dir is in PATH
check_path() {
    if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
        warn "$INSTALL_DIR is not in your PATH"

        # Detect shell config file
        SHELL_CONFIG=""
        if [[ -n "$ZSH_VERSION" ]] || [[ "$SHELL" == *"zsh"* ]]; then
            SHELL_CONFIG="$HOME/.zshrc"
        elif [[ -n "$BASH_VERSION" ]] || [[ "$SHELL" == *"bash"* ]]; then
            if [[ -f "$HOME/.bash_profile" ]]; then
                SHELL_CONFIG="$HOME/.bash_profile"
            else
                SHELL_CONFIG="$HOME/.bashrc"
            fi
        fi

        if [[ -n "$SHELL_CONFIG" ]]; then
            echo "" >> "$SHELL_CONFIG"
            echo "# Added by yaade installer" >> "$SHELL_CONFIG"
            echo "export PATH=\"\$PATH:$INSTALL_DIR\"" >> "$SHELL_CONFIG"
            success "Added $INSTALL_DIR to PATH in $SHELL_CONFIG"
            warn "Run 'source $SHELL_CONFIG' or restart your terminal to use yaade"
        else
            warn "Could not detect shell config. Add the following to your shell config:"
            echo "    export PATH=\"\$PATH:$INSTALL_DIR\""
        fi
    else
        success "$INSTALL_DIR is already in PATH"
    fi
}

# Main installation flow
main() {
    echo ""
    echo "======================================"
    echo "      Yaade CLI Installer"
    echo "======================================"
    echo ""

    check_python
    check_uv
    get_install_dir
    install_yaade
    create_wrapper
    check_path

    echo ""
    echo "======================================"
    success "Installation complete!"
    echo "======================================"
    echo ""
    echo "Usage:"
    echo "  yaade              - Launch TUI"
    echo "  yaade serve        - Run MCP server"
    echo "  yaade --help       - Show help"
    echo ""
}

main "$@"
